### ISSUE TITLE
Variations can cause WC_Data_Exception errors

### ISSUE THREAD

**Issue by mikejolley** [skyverge/woocommerce-product-sku-generator#16]
This was reported here.

After messing with existing attributes and adding some extra variations (some had duplicate attributes to existing variations), saving the product caused this:

> Fatal error: Uncaught WC_Data_Exception: Invalid or duplicated SKU. in /srv/www/wordpress-local/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php:794 Stack trace: #0 /srv/www/wordpress-local/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(820): WC_Data->error('product_invalid...', 'Invalid or dupl...', 400, Array) #1 /srv/www/wordpress-local/public_html/wp-content/plugins/woocommerce-product-sku-generator/woocommerce-product-sku-generator.php(464): WC_Product->set_sku('v-neck-t-shirt-...') #2 /srv/www/wordpress-local/public_html/wp-content/plugins/woocommerce-product-sku-generator/woocommerce-product-sku-generator.php(416): WC_SKU_Generator->maybe_save_variation_sku(183, Object(WC_Product_Variable), 'v-neck-t-shirt') #3 /srv/www/wordpress-local/public_html/wp-includes/class-wp-hook.php(286): WC_SKU_Generator->maybe_save_sku(Object(WC_Product_Variable), Object(WP_Post)) #4 /srv/www/wordpress-local/public_html/wp-includes/class-wp-hook.php(310): WP_Hook- in /srv/www/wordpress-local/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php on line 794

https://github.com/skyverge/woocommerce-product-sku-generator/blob/master/woocommerce-product-sku-generator.php#L416

Needs a try catch block as set_sku will trigger exception if a duplicate is set.

**Comment by bekarice** [comment]
@mikejolley thanks for the heads up! will patch in the next release
