### ISSUE TITLE
Error message on upgrading to WooC 3.6.4

### ISSUE THREAD

**Issue by peterb776** [skyverge/woocommerce-product-sku-generator#18]
I've just upgraded from WooC 3.5.7 (where everything was fine) to 3.6.4 and get the following error message:

"WooCommerce Product SKU Generator is inactive. This plugin requires WooCommerce 2.6.14 or newer. Please update WooCommerce or run the WooCommerce database upgrade."

Help!

Thanks,
Peter

**Comment by bekarice** [comment]
@peterb776 hey there! Please click the link in this message to run the database upgrade -- this message means that the woocommerce upgrade hasn't been run, so your site's database is out of date. That will resolve the message.

I'm going to close this since the notice has the link to resolve this, but please feel free to add further details if the message persists after that upgrade completes. 🍻

**Comment by peterb776** [comment]
Beka,

Thanks for the reply, but I had already run the database upgrade, and the WooC notification to run the upgrade no longer appeared.

If I now click on the 'run the WooCommerce database upgrade' link in the Product SKU Generator notification then I get the response 'The link you followed has expired.' That's why I raised this issue here.

The only odd thing is that when I look at the WooC status details there is no WooC database version shown: 
![FireShot Capture 040 - WooCommerce status ‹ — WordPress - artstrailgallerx local](https://user-images.githubusercontent.com/10865376/60570044-998fab80-9d68-11e9-942f-14cc11743305.jpg)
 and I have no idea how to fix that.

Regards,
Peter

**Comment by peterb776** [comment]
After googling around I found someone else with a very similar issue - a WooC upgrade losing the database version entry in the wp_options table. I used the SQL provided as the solution there to add a woocommerce_db_version field back in with the right value, disabled and then re-enabled Product SKU Generator and it seems to have resolved the issue.
 
Regards,
Peter

**Comment by bekarice** [comment]
@peterb776 thanks for the update, interesting that the version option didn't exist O_o. I think we could fall back to use the `WC_VERSION` constant instead, so I'm going to open a new issue to consider that as our version check rather than the option. thanks for letting me know what this was!
