### ISSUE TITLE
WooCommerce 2.5 Compatibility

### ISSUE THREAD

**Issue by tamarazuk** [skyverge/woocommerce-product-sku-generator#6]
Update for WooCommerce v2.5

**Comment by bekarice** [comment]
@tamarazuk tested, ready for review

**Comment by BurlesonBrad** [comment]
Already been running it (with PHP7) ((& WC beta)) 
In production? Yup!
I say it passes :-)

**Comment by bekarice** [comment]
@BurlesonBrad :dancer: w00t that's what we like to hear! Thanks for confirming :smile_cat:

**Comment by unfulvio** [comment]
I gave it a spin and looks good to me 

at first I thought something wasn't working because this check at the beginning isn't compatible with our Locally Grown vagrant box
```
// Check if WooCommerce is active
if ( ! in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) )
	return;
```

for example it can be ` 'woocommerce-master/woocommerce.php'` in our case

**Comment by tamarazuk** [comment]
@unfulvio this is because Locally Grown defines it's own `WC_Dependencies::woocommerce_active_check()` method to override the one in `woo-includes`. However, `woo-includes` is not used in .org extensions so you have to comment out that line while testing.
