### ISSUE TITLE
WooCommerce 2.6 Compatibility

### ISSUE THREAD

**Issue by bekarice** [skyverge/woocommerce-product-sku-generator#7]
- [x] **Misc** -- Drop WooCommerce 2.2 support

   * **Completed in** SHA 985d66dbfb8ee9d2e58637c8acd4fee8a6eb9c7b

 - [x] **Misc** -- Add any needed compat methods

   * **Completed in** SHA 322bcf7433d50d90a16366b1fdb0ade8448e59a6

 - [x] **Feature** -- adds ability to use dashes in attribute names to replace spaces

   * **Completed in** SHA 2f838a7e8f696b4bf9334bdf71f86379b543342d

**Comment by tamarazuk** [comment]
🎱  pending the tiny question in https://github.com/skyverge/woocommerce-product-sku-generator/commit/2f838a7e8f696b4bf9334bdf71f86379b543342d#commitcomment-17620015

**Comment by bekarice** [comment]
yep, just fixed and force PhpStorm to stop hijacking the `case` / `break` indents

**Comment by bekarice** [comment]
closed via 322bcf7433d50d90a16366b1fdb0ade8448e59a6 and deployed
