### ISSUE TITLE
WooCommerce 2.7 Compatibility

### ISSUE THREAD

**Issue by bekarice** [skyverge/woocommerce-product-sku-generator#8]
## To Do

 - [x] Update to use product getters instead of class properties directly (may require WC 2.5+)
   * **Completed in**: SHA 0dbbbaa8d0cb4819c5305a8cdd9d733050a22214

 - [x] Check usage of Select2 on settings for update
   * **Tweak in**: SHA 0dbbbaa8d0cb4819c5305a8cdd9d733050a22214

 - [x] Test with new product CRUD methods

 - [x] Add doc blocks for hooks that don't have them
   * **Completed in**: SHA 281b8fad7c62bec5277ff72915f27ecf455bf323

 - [x] Ensure out of stock variations have SKUs generated on product save

   * **Completed in**: SHA d4651d0e6a3073738ab1f501b62beb94f09bee94

## If time allows

 - [x] Add setting to strip spaces from attribute names
   * **Completed in**: SHA 3e76e366ed4f439252839e6f04fecdfd0b37d838

**Comment by justinstern** [comment]
🗂
